export {default as HomePage} from './Home'
export {default as SignIn} from './SignIn'
export {default as SignUp} from './SignUp'
export {default as ProfilePage} from './Profile'
export {default as Authentication} from './Authentication'