export default {
    DARK: 'dark-content',
    LIGHT: 'light-content',
    DEFAULT: 'default',
    WLCBACK: 'Welcome back!',
    CREACC: 'Create your new Account',
    LOGIN: 'Login to your Account',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CPASSWORD: 'Confirm password',
    SIGNIN: 'Sign in',
    SIGNUP: 'Sign up',
    GO: 'Go',
    FORGOT: 'Forget password. Need help ?',
    DONTACC: "Don't have an account ? ",
    APPNAME: 'Paragram',
    FULLNAME: 'Full name',
    EMAIL: 'Email',
    BIRTHDAY: 'Birthday',
    GENDER: 'Gender',
    ORSIGNWITH: 'Or sign in with',
    HAVEACC: 'Have an Account ? ',
    SIGNINOW: 'Sign in now',
    BACK: 'Back',
    SIGNOUT: 'Sign Out',
    REMEMBERME: 'Remember me',
    ABOUT:  'Information',
    DETAILS:'Details of your profile',
    SEARCHING: 'Searching a friend....'
}