export default {
    RIGHT_ARROW : require('../assets/icons/right-arrow.png'),
    AUTHEN_USERNAME : require('../assets/icons/username.png'),
    AUTHEN_PASSWORD : require('../assets/icons/password.png'),
    OUTSIDE : require('../assets/icons/outside.png'),
    INSIDE : require('../assets/icons/inside.png'),
    LOGO : require('../assets/icons/logo.png'),
    FULLNAME : require('../assets/icons/fullname.png'),
    EMAIL : require('../assets/icons/email.png'),
    GENDER : require('../assets/icons/gender.png'),
    BIRTHDAY : require('../assets/icons/birthday.png'),
    FACEBOOK : require('../assets/icons/facebook.png'),
    GOOGLE : require('../assets/icons/google.png'),
    TWITTER : require('../assets/icons/twitter.png'),
    FRIENDS: require('../assets/icons/friends.png'),
    HOME: require('../assets/icons/home.png'),
    BACK:   require('../assets/icons/back.png'),
    PROFILE:   require('../assets/icons/profile.png'),
    INFORMATION : require('../assets/icons/information.png'),
    SEARCH : require('../assets/icons/search.png'),
}